// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4t5c1sVPAFfZNb6XZ7-8-NvQqzOyfvm8',
    appId: '1:45420055162:web:1c5e4ae081c750fff709c3',
    messagingSenderId: '45420055162',
    projectId: 'multi-vendor-ecommerce-a-7fb0d',
    authDomain: 'multi-vendor-ecommerce-a-7fb0d.firebaseapp.com',
    storageBucket: 'multi-vendor-ecommerce-a-7fb0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgj7K2WevQq8kRCzXRcfy4LC82bPYx1g',
    appId: '1:45420055162:android:ee3e1a09246eda7cf709c3',
    messagingSenderId: '45420055162',
    projectId: 'multi-vendor-ecommerce-a-7fb0d',
    storageBucket: 'multi-vendor-ecommerce-a-7fb0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6xR2vgAQ5LO-dg4SUCXrkUXdYNi5U-0',
    appId: '1:45420055162:ios:3b6a4227cc76c6f9f709c3',
    messagingSenderId: '45420055162',
    projectId: 'multi-vendor-ecommerce-a-7fb0d',
    storageBucket: 'multi-vendor-ecommerce-a-7fb0d.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorEcommerceAppAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK6xR2vgAQ5LO-dg4SUCXrkUXdYNi5U-0',
    appId: '1:45420055162:ios:3b6a4227cc76c6f9f709c3',
    messagingSenderId: '45420055162',
    projectId: 'multi-vendor-ecommerce-a-7fb0d',
    storageBucket: 'multi-vendor-ecommerce-a-7fb0d.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorEcommerceAppAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4t5c1sVPAFfZNb6XZ7-8-NvQqzOyfvm8',
    appId: '1:45420055162:web:e63a1326a2771e93f709c3',
    messagingSenderId: '45420055162',
    projectId: 'multi-vendor-ecommerce-a-7fb0d',
    authDomain: 'multi-vendor-ecommerce-a-7fb0d.firebaseapp.com',
    storageBucket: 'multi-vendor-ecommerce-a-7fb0d.firebasestorage.app',
  );
}
